### ISSUE TITLE
why random sample during training and center sample during validation?

### ISSUE THREAD

**Issue by menggehe** [gingsi/coot-videotext#25]
why random sample during training and center sample during validation? What are the effects of different sampling methods？

**Comment by gingsi** [comment]
Random sampling during training works better empirically, it's a form of regularization to prevent overfitting. You can verify this by training with center sampling and you should get worse performance.

We do center sampling during validation so that inference is deterministic i.e. it doesn't depend on the random seed.

**Comment by menggehe** [comment]
> Random sampling during training works better empirically, it's a form of regularization to prevent overfitting. You can verify this by training with center sampling and you should get worse performance.
> 
> We do center sampling during validation so that inference is deterministic i.e. it doesn't depend on the random seed.

Thank you very much!
